### ISSUE TITLE
Would it be possible to add a license to the proyect to know how we can use and/or contribute to the code?

### ISSUE THREAD

**Issue by elchudi** [openkratio/proyecto-colibri#21]

**Comment by pulimento** [comment]
Pretty sure we're offering the code to be open to the community, but let me ask to the mantainers of this project

@ewokcillo @pr3ssh ??

**Comment by ewokcillo** [comment]
Hi,

I added a LICENCE file with "GNU General Public License v3.0".

Regards!!!
